### ISSUE TITLE
Error when trying to analyse SIR_R0 example

### ISSUE THREAD

**Issue by Xabo-RB** [alexeyovchinnikov/SIAN-Julia#68]
I was trying to analyse the example code of SIR_R0 taken from here:
https://github.com/alexeyovchinnikov/SIAN-Julia/blob/main/examples/SIR_R0.jl

and I am getting the following error. I have also checked the other examples and they worked correctly. I don't know how to fix it so I would appreciate your help.

ERROR: ArgumentError: The polynomial contains a variable not present in the new ring -In_0 + 89341292
Stacktrace:
 [1] parent_ring_change(poly::fmpq_mpoly, new_ring::Singular.PolyRing{Singular.n_Q})
   @ SIAN ~/.julia/packages/SIAN/HlRlg/src/util.jl:119
 [2] (::SIAN.var"#118#149")(e::fmpq_mpoly)
   @ SIAN ./none:0
 [3] iterate
   @ ./generator.jl:47 [inlined]
 [4] collect(itr::Base.Generator{Vector{fmpq_mpoly}, SIAN.var"#118#149"})
   @ Base ./array.jl:724
 [5] identifiability_ode(ode::ODE{fmpq_mpoly}, params_to_assess::Vector{fmpq_mpoly}; p::Float64, p_mod::Int64, nthrds::Int64, infolevel::Int64)
   @ SIAN ~/.julia/packages/SIAN/HlRlg/src/SIAN.jl:467
 [6] top-level scope
   @ REPL[3]:1

**Comment by iliailmer** [comment]
Hi @Xabo-RB , which version of julia are you using? We recently pushed some changes to the SIAN code, the latest package version to be used is now 1.3.0 and up. Please let me know if the error still persists.

**Comment by Xabo-RB** [comment]
Thank you, @iliailmer. I fixed the bug by upgrading the package to the latest version. I was using SIAN v1.1.7.
