### ISSUE TITLE
Given initial conditions?

### ISSUE THREAD

**Issue by qchenmath** [alexeyovchinnikov/SIAN-Julia#71]
Any way to fix some initial conditions in this Julia version of SIAN? Our school doesn't have Maple.

**Comment by qchenmath** [comment]
Gleb helped me with the model. It will be nice to have such functionality. Often, by giving values to certain initial conditions (for the state variables), non-identifiable parameters may become globally identifiable.

**Comment by iliailmer** [comment]
Good to know that the issue was resolved. I will close this for now.
