### ISSUE TITLE
measured_quantities as keyword argument in identifiability_ode

### ISSUE THREAD

**Issue by MarcusGalea** [alexeyovchinnikov/SIAN-Julia#72]
Hello,
I was wondering if you could add measured_quantities as an optional input to identifiability_ode? It makes it a lot easier to use, especially when working with packages like catalyst, where the ODE is provided, and not explicitly written by the user. Otherwise, great package.

**Comment by iliailmer** [comment]
Hi @MarcusGalea , thank you for your question. Could you please provide an example of how you use SIAN.jl with Catalyst? The reason why `measured_quantities` are a required argument is because without a measurement we cannot determine identifiability property.

**Comment by MarcusGalea** [comment]
This is what I intend to do, but done using StructuralIdentifiability.
```
using StructuralIdentifiability
#underlying model describing the data
# One binding/hydrolysis event:
model = @reaction_network begin
    k1, E + S --> ES
    k2, ES --> S + E
    k3, ES --> E + P
end k1 k2 k3
odesys = convert(ODESystem, model)
measured_quantities = [sum(species(model)]

assess_identifiability(odesys,measured_quantities = measured_quantities)
```

In SIAN this way more complicated to do, since `measured_quantities` needs to be written explicitly within the ODESystem.

**Comment by iliailmer** [comment]
@MarcusGalea The keyword is now supported, please let me know if the version 1.3.2 resolves the issue for you.
