### ISSUE TITLE
Printing output in the README for examples

### ISSUE THREAD

**Issue by finmod** [alexeyovchinnikov/SIAN-Julia#9]
Trying to run some of the examples, I run into difficulties with the dependencies, GAP in particular, that cannot be installed properly on my standard Julia 1.6 environment.

Can you print an example of the output of identifiability_ode so that we can see what to expect?

Thanks

**Comment by iliailmer** [comment]
@finmod Thank you for pointing that out. I added an example to the README.md, please see here: https://github.com/alexeyovchinnikov/SIAN-Julia, under `Example: getting started` section.
